### PR TITLE
added click-handler for backdrop

### PR DESCRIPTION
**Pull request by mavuio**
clicking on the backdrop now also closes the modal window

### CODE REVIEW

**Comment by SRichner** [comment]
@javisperez could you take a look at this PR and #17 and merge if possible? Thank you!

**Comment by javisperez** [comment]
@SRichner oh yeah, I'll have a look, sorry, been really busy but I'll try to do it asap, thank you for the reminder!

**Comment by SRichner** [comment]
@javisperez No worries. Thank you 👍 let me know if you need help.

**Comment by javisperez** [comment]
Merged and deploy! sorry for the delay and thank you for the contribution!

**Pull request merged**
